#!/bin/sh

set -e

PKGNAME="$1"
VERSION="$2"

[ -x /usr/bin/ukify ] || exit 0

# Read kernel command line from file if it exists, otherwise use a safe default
CMDLINE="loglevel=4"
if [ -f "${ROOTDIR}/etc/kernel/cmdline" ]; then
    CMDLINE=$(cat "${ROOTDIR}/etc/kernel/cmdline")
fi

ukify build \
	--linux="${ROOTDIR}/boot/vmlinuz-${VERSION}" \
	--initrd="${ROOTDIR}/boot/initramfs-${VERSION}.img" \
	--output="${ROOTDIR}/boot/efi/EFI/Linux/void-linux.efi" \
	--uname="${VERSION}" \
	--cmdline="$CMDLINE"
