#!/bin/bash

# --- GRAPHICS DRIVERS ---
graphicsArray=($graphics)

[ -n "$graphics" ] && commandFailure="Graphics driver installation has failed."
for i in "${graphicsArray[@]}"; do
    case $i in
        amd)
            install mesa-dri vulkan-loader mesa-vulkan-radeon mesa-vaapi
            ;;
        intel)
            install mesa-dri vulkan-loader mesa-vulkan-intel intel-video-accel
            ;;
        nvidia)
            install void-repo-nonfree
            if [ "$kernel" == "linux-lts" ]; then
                install nvidia-lts
            else
                install nvidia
            fi
            setKernelParam "nvidia_drm.modeset=1"
            ;;
        nvidia-nouveau)
            install mesa-dri mesa-nouveau-dri
            ;;
        none|auto)
            # Generic fallback, usually sufficient for VMs (virtio, qxl, vmware) or unknown hardware
            install mesa-dri
            ;;
        *)
            echo "Unknown graphics option: $i, installing generic mesa-dri..."
            install mesa-dri
            ;;
    esac
done

# --- NETWORK ---
[ -n "$network" ] && [ "$network" != "none" ] && commandFailure="DHCP client setup has failed."
case "$network" in
    NetworkManager) install NetworkManager; enableService NetworkManager ;;
    dhcpcd) enableService dhcpcd ;;
esac

# --- GUI INSTALLATION ---
commandFailure="GUI installation has failed"
# Use 'kde-plasma' instead of the transitional 'kde5' package
install kde-plasma xdg-user-dirs xdg-utils chromium elogind polkit-elogind
enableService elogind
enableService polkitd

# --- AUDIO SERVER ---
commandFailure="Audio server installation has failed."
install pipewire wireplumber alsa-pipewire

# ALSA configuration for pipewire
system "mkdir -p /etc/alsa/conf.d"
system "ln -sf /usr/share/alsa/alsa.conf.d/50-pipewire.conf /etc/alsa/conf.d/50-pipewire.conf"
system "ln -sf /usr/share/alsa/alsa.conf.d/99-pipewire-default.conf /etc/alsa/conf.d/99-pipewire-default.conf"

return 0
