#!/bin/bash
# Basic checks and setup before the installer reaches configuration

echo "Running basic checks..."

if [ "$(id -u)" -ne 0 ]; then
    echo -e "${RED}Please execute this script as root.${NC}"
    exit 1
fi

dependencies=("setup/base" "setup/desktop" "setup/disk" "setup/chroot" "misc/60-ukify" "misc/libviss")

for i in "${dependencies[@]}"; do
    [ -e "$i" ] ||
        { commandFailure="$i appears to be missing. This could be because it is incorrectly named, or it does not exist." ; die ; }
    bash -n "$i" 2>/dev/null ||
        { commandFailure="Syntax error in $i (e.g. unclosed quote). Run 'bash -n $i' to find the exact line." ; die ; }
done

[ -e "/sys/firmware/efi" ] ||
    { commandFailure="This script only supports UEFI systems, but it appears we have booted as BIOS." ; die ; }

[ "$(uname -m)" != "x86_64" ] &&
    { commandFailure="This systems CPU architecture is not currently supported by this installer." ; die ; }

echo "Finding out what libc is being used..."
if ldd --version 2>&1 | grep -q GNU ; then
    libc="glibc"
else
    libc="musl"
fi

echo "Testing for network connectivity..."
if ! xbps-install -S > /dev/null 2>&1; then
    commandFailure="Network check failed: Cannot synchronize Void repositories."
    die
fi

commandFailure="Dependency installation has failed."
xbps-install -Suy xbps || die
xbps-install -Suy dialog || die

dialog --create-rc "$HOME/.dialogrc"

logFile="/tmp/void-install-script.log"

return 0
